language: node_js
node_js:
  - "node"
install:
  - npm install -g codecov istanbul
script:
  - npm install
  - npm test
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov